### ISSUE TITLE
Unable to set up RTL8188GU driver

### ISSUE THREAD

**Issue by horugane** [a5a5aa555oo/rtl8xxxu#1]
I am new to using Linux. I tried to install a new driver for my wifi adapter and since it is a RTL8188GU driver, I also attempted with usb-modeswitch, but it does not work.

At first I only did `sudo usb_modeswitch -v 0bda -p b832`. It appeared to be fine but no wifi popping up on the taskbar. Tried modeswitch again and I got the following errors:

`Take all parameters from the command line

 * usb_modeswitch: handle USB devices with multiple modes
 * Version 2.6.1 (C) Josua Dietze 2017
 * Based on libusb1/libusbx

 ! PLEASE REPORT NEW CONFIGURATIONS !

DefaultVendor=  0x0bda
DefaultProduct= 0xb832

StandardEject=1

Look for default devices ...
  found USB ID 174c:3074
  found USB ID 1d6b:0003
  found USB ID 0951:170f
  found USB ID 258a:1006
  found USB ID 12d1:108a
  found USB ID 174c:2074
  found USB ID 0bda:b832
   vendor ID matched
   product ID matched
  found USB ID 0b05:19af
  found USB ID 046d:c53f
  found USB ID 05ac:2405
  found USB ID 1d6b:0002
 Found devices in default mode (1)
Access device 011 on bus 001
Get the current device configuration ...
Current configuration number is 1
Use interface number 0
 with class 255
Error: can't use storage command in MessageContent with interface 0; interface class is 255, expected 8. Abort`

Here's the `lsusb` of the adapter in question: `01 Device 011: ID 0bda:b832 Realtek Semiconductor Corp. 802.11ac WLAN Adapter`. I'm using Arch Linux.

**Comment by a5a5aa555oo** [comment]
I think your device is in wifi mode already, so you don't need to change it via usb_modeswitch, 
and it uses a RTL8832BU or RTL8852BU chip actually, so the driver in this repo is not applicable to your device.

You can try this driver, it should work for you
https://github.com/morrownr/rtl8852bu/

**Comment by horugane** [comment]
Thanks, the driver you sent above worked and there seems to be no problem for now, but it is interesting because initially I did `lsusb` and it showed the driver name next to the Wifi adapter as such, but turned out it is 8852bu instead. What a roller coaster haha.

Speaking of which, there is an issue with almost all wifi adapters I have is that the internet speed (particularly download speed) is abysmally low. I'm talking like 2-3MB/s, for this one peak at 10.4MB/s (referencing Steam downloads in this case). My home internet speed is 300Mbps, and on Windows the download speed on Steam typically falls around 15-20MB/s, sometimes even reaching 25-30MB/s; it also applies to normal browser's direct install in good servers. Is this like a Linux limitation regarding Wifi, or is this driver related?

**Comment by a5a5aa555oo** [comment]
Glad your device works now. 
I have no 8832BU/8852BU devices, so I don't know what speed they should have under Linux.
Maybe you can open another issue on that repo. :)
